routes/index.py
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    make_response,
    send_from_directory,
    abort,
)
from werkzeug.utils import secure_filename
from models.user import User
from config import user_file_director
import os

from utils import log

main = Blueprint('index', __name__)


def current_user():
    # 从 session 中找到 user_id 字段, 找不到就 -1
    # 然后 User.find_by 来用 id 找用户
    # 找不到就返回 None
    uid = session.get('user_id', -1)
    u = User.find_by(id=uid)
    return u


"""
用户
    访问首页
    注册
    登录

"""


@main.route("/")
def index():
    return render_template("/topic/index.html")

@main.route("/inlog")
def inlog():
    u = current_user()
    print('debug inlog topic', u)
    return render_template("index.html", user=u)


@main.route("/register", methods=['POST'])
def register():
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    return render_template("index.html")


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        # 转到 topic.index 页面
        # return redirect(url_for('topic.index'))
        abort(403, 'register again')
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('topic.index'))

@main.route('/logout')
def logout():
    if session.get('user_id') is None:
        return redirect(url_for('index.inlog'))
    else:
        print(session, 'session')
        session.pop('user_id')
        print("pop", logout)
        return render_template("/topic/index.html")


@main.route('/profile')
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        return render_template('profile.html', user=u)


def allow_file(filename):
    suffix = filename.split('.')[-1]
    from config import accept_user_file_type
    return suffix in accept_user_file_type


@main.route('/addimg', methods=["POST"])
def add_img():
    u = current_user()

    if u is None:
        return redirect(url_for(".profile"))

    if 'file' not in request.files:
        return redirect(request.url)

    file = request.files['file']
    if file.filename == '':
        return redirect(request.url)

    if allow_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(user_file_director, filename))
        u.user_image = filename
        u.save()

    return redirect(url_for(".profile"))


@main.route("/uploads/<filename>")
def uploads(filename):
    return send_from_directory(user_file_director, filename)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    {% block css %} {% endblock %}
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    {% block script %} {% endblock %}
    <style>
        header {
            background: #0f88eb;
        }

        a.gua-header-item {
            display: inline-block;
            color: white;
            padding: 25px;
            text-align: center;
            text-decoration: none;
        }

        a.gua-header-item1 {
            display: inline-block;
            color: white;
            padding: 25px;
            float: right;
            text-decoration: none;
        }

        .gua-header-item:hover {
            background-color: white;
            color: black;
            /* 鼠标指针变为链接手 */
            cursor: pointer;
        }
        /* 底部 */

        footer {
            background: white;
            text-align: center;
            position: fixed;
            bottom: 0px;
            width: 100%;
            border-top: 1px solid lightgray;
        }
    </style>
</head>
<body>
    <div class="bbs-top">
        <header class="bbs-menu">
            <a class="gua-header-item" href="{{ url_for('topic.index') }}">首页</a>
            <a class="gua-header-item" href="{{ url_for('index.inlog') }}">登录/注册</a>
            <a class="gua-header-item" href="{{ url_for('index.logout') }}">退出</a>
            <a class="gua-header-item1" href="/py/profile">用户</a>
            <a class="gua-header-item1" href="/py/mail">私信</a>
        </header>
    </div>

    <div class="bbs-main">

        <div class="content">
            {% block content %} {% endblock %}
        </div>

        <div class="sidebar">
            {% block sidebar %} {% endblock %}
        </div>

    </div>


    <footer>
        <a href="#">关于</a>
        <span>&nbsp;·&nbsp;</span>
        <a href="#">FAQ</a>
        <span>&nbsp;·&nbsp;</span>
        <a href="#">鸣谢</a>
        <span>&nbsp;·&nbsp;</span>
        World is powered by solitude
        <span>&nbsp;·&nbsp;</span>
        Python的个人BBS
        <br>
        <a href="#"> pytao.cc</a>
    </footer>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BBS正门</title>
    <style type="text/css">
        a {
            text-decoration: none;
            color: #000;
        }
        .active {
            color: dodgerblue;
        }
        .gua-container {
            text-align: center;
        }
        .gua-main {
            width: 300px;
            margin: auto;
        }
        .gua-header h1 {
            font-size: 40px;
            color: dodgerblue;
        }
        .gua-header h2 {
            font-size: 18px;
        }
        .gua-tab {
            margin-top: 30px;
        }
        .gua-tab a {
            margin: 10px;
        }
        .gua-block {
            height: 3px;
            width: 45px;
            position: relative;
            left: 100px;;
            background-color: dodgerblue;
        }
        .gua-form-textinput {
            margin-top: 20px;
            border-style: solid;
            border-radius: 3px;
            border-width: 1px;
            border-color: lightgray;
        }
        .gua-input-wrapper + .gua-input-wrapper {
            border-style: solid;
            border-width: 0px;
            border-top-width: 1px;
            border-color: lightgray;
        }
        .gua-input-wrapper input {
            width: 90%;
            height: 35px;
            margin: 5px;
            border: none;
            outline: none;
        }
        .gua-button-big {
            width: 100%;
            height: 35px;
            margin-top: 20px;
            margin-bottom: 20px;
            background-color: dodgerblue;
            color: white;
            border: none;
            border-radius: 3px;
            font-size: 16px;
        }

        .float-left {
            float: left;
        }

        .float-right {
            float: right;
        }

        .captcha-link {
            display: inline-block;
            padding: 5px;
        }

        .captcha-link img:hover {
            cursor: pointer;
        }
    </style>
</head>
<body>
    <div class="gua-container">
        <div class="gua-main">
            <div class="gua-header">
                <h1 class="gua-title">BBS</h1>
                <h2 class="gua-subtitle">暂时开放注册</h2>
            </div>
            <div class="gua-form">
                <div class="gua-tab">
                    <a id="id-a-signup" href="#">注册</a>
                    <a id="id-a-login" href="#">登录</a>
                    <div class="gua-block"></div>
                </div>
                <div id="id-div-signup">
                    <form  method="post" action="{{ url_for('index.register') }}">
                    <div class="gua-form-textinput">
                        <div class="gua-input-wrapper">
                            <input id="id-input-username" type="text" name="username" placeholder="用户名（不少于 3 位）" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-password" type="text" name="password" placeholder="密码（不少于 5 位）" required/>
                        </div>
                    </div>
                    <button id="id-button-register" class="gua-button-big" type="submit" >注册</button>
                    </form>
                </div>

                <div id="id-div-login">
                    <form method="post" action="{{ url_for('index.login') }}">
                    <div class="gua-form-textinput">
                        <div class="gua-input-wrapper">
                            <input id="id-input-login-username" type="text" name="username" placeholder="用户名" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-login-password" type="text" name="password" placeholder="密码" required/>
                        </div>
                    </div>
                    <button id="id-button-login" class="gua-button-big" type="submit">进入</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>高级炼瓜研究所正门</title>
    <style type="text/css">
        a {
            text-decoration: none;
            color: #000;
        }
        .active {
            color: dodgerblue;
        }
        .gua-container {
            text-align: center;
        }
        .gua-main {
            width: 300px;
            margin: auto;
        }
        .gua-header h1 {
            font-size: 40px;
            color: dodgerblue;
        }
        .gua-header h2 {
            font-size: 18px;
        }
        .gua-tab {
            margin-top: 30px;
        }
        .gua-tab a {
            margin: 10px;
        }
        .gua-block {
            height: 3px;
            width: 45px;
            position: relative;
            left: 100px;;
            background-color: dodgerblue;
        }
        .gua-form-textinput {
            margin-top: 20px;
            border-style: solid;
            border-radius: 3px;
            border-width: 1px;
            border-color: lightgray;
        }
        .gua-input-wrapper + .gua-input-wrapper {
            border-style: solid;
            border-width: 0px;
            border-top-width: 1px;
            border-color: lightgray;
        }
        .gua-input-wrapper input {
            width: 90%;
            height: 35px;
            margin: 5px;
            border: none;
            outline: none;
        }
        .gua-button-big {
            width: 100%;
            height: 35px;
            margin-top: 20px;
            margin-bottom: 20px;
            background-color: dodgerblue;
            color: white;
            border: none;
            border-radius: 3px;
            font-size: 16px;
        }

        .float-left {
            float: left;
        }

        .float-right {
            float: right;
        }

        .captcha-link {
            display: inline-block;
            padding: 5px;
        }

        .captcha-link img:hover {
            cursor: pointer;
        }
    </style>
    <script src="/static/js/jquery-3.0.0.min.js"></script>
    <script src="/static/js/vipapi.js"></script>
    <script>
        // setup
        var setup = function() {
            // tab click
            $('.gua-tab > a').on('click', function () {
                var self = $(this);
                $('.active').removeClass('active');
                self.addClass('active');
            });

            // tab action
            var tabAction = function (position, showLogin) {
                $(".gua-block").animate({
                    "left": position
                }, "fast");
                $('#id-div-login').toggle(showLogin);
                $('#id-div-signup').toggle(!showLogin);
            };

            $('#id-a-signup').on('click', function() {
                var position = '100px';
                var showLogin = false;
                tabAction(position, showLogin);
            });
            $('#id-a-login').on('click', function() {
                var position = '155px';
                var showLogin = true;
                tabAction(position, showLogin);
            });
        };

        var loginForm = function () {
            var keys = [
                'username',
                'password',
                'code',
            ];
            var loginPrefix = 'id-input-login-';
            var form = formFromKeys(keys, loginPrefix);
            return form;
        };

        var registerForm = function() {
            var keys = [
                'username',
                'signature',
                'password',
                'email',
                'qq',
                'captcha',
            ];
            var registerPrefix = 'id-input-';
            var form = formFromKeys(keys, registerPrefix);
            return form;
        };

        // actions
        var register = function(){
            var form = registerForm();
            var success = function (r) {
                log('reg, ', r);
                if(r.success) {
                    log(r.next);
                    window.location.href = r.next;
                } else {
                    alert(r.message);
                }
            };
            var error = function (err) {
                log('reg, ', err);
            };
            vip.register(form, success, error);
        };

        var login = function(){
            var form = loginForm();
            var success = function (r) {
                log('login, ', r);
                if(r.success) {
                    log(r.next);
                    window.location.href = r.next;
                } else {
                    $('.captcha-link').trigger('click')
                    alert(r.message);
                }
            };
            var error = function (err) {
                log('login, ', err);
                alert(err);
            };
            vip.login(form, success, error);
        };

        var bindActions = function() {
            $('#id-button-register').on('click', function(){
                register();
            });

            $('#id-button-login').on('click', function(){
                login();
            });

            $('.captcha-link').on('click', function(event) {
                var time = Date.now()
                var path = `/captcha?t=${time}`
                $(this).find('img').attr('src', path)
                event.preventDefault()
            })
        };

        var __main = function() {
            setup();
            bindActions();
            // select signup
            $('#id-a-login').click();
        };

        $(document).ready(function(){
            __main();
        });
    </script>
</head>
<body>
    <div class="gua-container">
        <div class="gua-main">
            <div class="gua-header">
                <h1 class="gua-title">高级炼瓜研究所</h1>
                <h2 class="gua-subtitle">暂时开放注册</h2>
            </div>
            <div class="gua-form">
                <div class="gua-tab">
                    <a id="id-a-signup" href="#">注册</a>
                    <a id="id-a-login" href="#">登录</a>
                    <div class="gua-block"></div>
                </div>
                <div id="id-div-signup">
                    <div class="gua-form-textinput">
                        <div class="gua-input-wrapper">
                            <input id="id-input-username" type="text" placeholder="用户名（不少于 6 位）" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-signature" type="text" placeholder="昵称（需要和 QQ 群内名称保持一致）" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-password" type="text" placeholder="密码（不少于 6 位）" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-email" type="text" placeholder="邮箱" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-qq" type="text" placeholder="群里的用的 QQ" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-captcha" type="text" placeholder="验证码（输入数字 3）" required/>
                        </div>
                    </div>
                    <button id="id-button-register" class="gua-button-big">注册</button>
                </div>
                <div id="id-div-login">
                    <div class="gua-form-textinput">
                        <div class="gua-input-wrapper">
                            <input id="id-input-login-username" type="text" placeholder="用户名" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <input id="id-input-login-password" type="text" placeholder="密码" required/>
                        </div>
                        <div class="gua-input-wrapper">
                            <a href="#" class="captcha-link">
                                <img src="/captcha?t=1515684464" alt="">
                            </a>
                            <input id="id-input-login-code" type="text" placeholder="验证码" required/>
                        </div>
                    </div>
                    <button id="id-button-login" class="gua-button-big" type="submit">进入</button>
                    <div class="gua-remember float-left">
                        <!-- <label><input id="gua-id-remember" type="checkbox" name="remember" />记住我</label> -->
                    </div>
                    <h5>忘记密码?</h5>
                    <form action="/send_reset_mail" method="post">
                    <div class="gua-form-textinput">
                        <div class="gua-input-wrapper">
                            <input name="qq" placeholder="输入你的 qq 号" required>
                        </div>
                    </div>
                        <button class="gua-button-big">点此发送重置密码邮件</button>
                    </form>
                </div>
            </div>
            <!-- 重置密码 -->
        </div>
    </div>
</body>
</html>

templates/profile.html
{% extends "base.html" %}

{% block title %}
    profile
{% endblock %}


{% block content %}
    <h3>目前仅支持上传头像</h3>
    <h2>用户资料页面</h2>
    <div>
        用户名:
        {{ user.username }}
        <br>
    </div>
    <div>
        用户图片：
        <br>
        <a >
        <img src={{ '/py/uploads/' + user.user_image }} width="200" height="250">
        </a>
        <br>
    </div>


    <br>
    <h2>上传头像</h2>
    <form method=post action={{ url_for(".add_img") }} enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>
{% endblock %}