models/topic.py
import time
from models import Model
from models.user import User
from utils import log


class Topic(Model):
    __fields__ = Model.__fields__ + [
        ('content', str, ''),
        ('title', str, ''),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('views', int, 0)
    ]

    @classmethod
    def get(cls, id):
        m = cls.find_by(id=id)
        m.views += 1
        m.save()
        return m

    def replies(self):
        from .reply import Reply
        ms = Reply.find_all(topic_id=self.id)
        return ms

    def board(self):
        from .board import Board
        m = Board.find(self.board_id)
        return m

    def user(self):
        u = User.find(id = self.user_id)
        return u

    def ct(self):
        format = '%Y/%m/%d %H:%M:%S'
        value = time.localtime(self.created_time)
        dt = time.strftime(format, value)
        return dt

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from routes import *


from models.reply import Reply


main = Blueprint('reply', __name__)


@main.route("/add", methods=["POST"])
def add():
    u = current_user()
    if u is None:
        abort(403, "Sorry, you don\'t have permission.")
    else:
        form = request.form
        m = Reply.new(form, user_id=u.id)
        return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    abort,
)

from utils import log
from routes import *

from models.topic import Topic
from models.board import Board
from models.reply import Reply


main = Blueprint('topic', __name__)


import uuid
csrf_tokens = dict()

@main.route("/")
def index():
    # board_id = 2
    board_id = int(request.args.get('board_id', -1))
    log('request.args', request.args)
    log('ms board_id', board_id)
    if board_id == -1:
        ms = Topic.all()
        log('if ms 查看', ms)
    else:
        ms = Topic.find_all(board_id=board_id)
        log('else ms 查看', ms)
    bs = Board.all()
    u = current_user()
    if u is None:
        return render_template("topic/index.html", ms=ms, bs=bs)

    else:
        token = str(uuid.uuid4())
        csrf_tokens[token] = u.id
        return render_template("topic/index.html", ms=ms, token=token, bs=bs)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/add", methods=["POST"])
def add():
    u = current_user()
    if u is None:
        abort(403, "Sorry, Don\'t have permission.")
    else:
        form = request.form
        m = Topic.new(form, user_id=u.id)
        log('add m type', type(m),m.id, m)
        return redirect(url_for('.detail', id=m.id))


@main.route("/delete")
def delete():
    u = current_user()
    if u is None:
        abort(403, "Sorry, Don\'t have permission.")
    else:
        # m = Topic.get('user_id')
        id = int(request.args.get('id'))
        token = request.args.get('token')
        ms = Topic.find_by(id=id)
        # 判断 token 是否是我们给的
        if token in csrf_tokens and csrf_tokens[token] == ms.user_id:
            csrf_tokens.pop(token)
            t = Topic.find_by(id=id)
            print('mongo t', t)
            t.delete()
            # 删除评论
            delr = Reply.find_all(topic_id=id)
            print('delr mongo', delr)
            for i in range(len(delr)):
                delr[i].delete()
            return redirect(url_for('.index'))
        else:
            abort(404,"Sorry, not you")



@main.route("/new")
def new():
    u = current_user()
    if u is None:
        abort(403, "Sorry, Don\'t have permission.")
    else:
        bs = Board.all()
        return render_template("topic/new.html", bs=bs)

templates/topic/detail.html
{% extends "base.html" %}

{% block title %}
    topic
{% endblock %}

{% block content %}
<div id="main">

    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/py/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>

    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
                <span class="topic_full_title">
                    {{ topic.title }}
                </span>
                <div class="changes">
                    <span>
                        {{ topic.ct() }}
                    </span>
                    <span>
                        作者
                        {{ topic.user().username }}
                    </span>
                    <span>
                        {{ topic.views }} 次浏览
                    </span>
                    <span>
                        板块From： {{ topic.board().title }}
                    </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">
                        <p id='id-topic-text-{{topic.id}}' class='p-topic-text' data-key='{{topic.id}}'>{{ topic.content }}</p>
                    </div>
                </div>
            </div>
        </div>


        <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        <div class='cell reply_area reply_item'>
            <div class='author_content'>
                <a class="user_avatar">
                    <img src={{ '/py/uploads/' + r.user().user_image + '?v=3&amp;s=120' }}title="atian25"
                    title="{{ r.user().username }}"/>
                </a>
                <div class='user_info'>
                    <a class='dark reply_author'>
                        {{ r.user().username }}
                    </a>
                    <a class="reply_time">
                        {{ loop.index }}楼 • {{ r.ct() }}
                    </a>
                </div>
            </div>

            <div class=' reply_content'>
                <div class="markdown-text">
                <p id='id-editor-text-{{r.id}}' class='p-text' data-key='{{r.id}}'>{{ r.content }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

        <div class='panel'>
            <div class='header'>
                <span class='col_fade'>添加回复</span>
            </div>

            <div class='inner reply'>
                <form id='reply_form' action="{{ url_for('reply.add') }}" method='post'>
                    <div class='markdown_editor in_editor'>
                        <div class='markdown_in_editor'>
                            <textarea class='editor' name='content'></textarea>
                            <div class='editor_buttons'>
                                <input class='span-primary submit_btn' type="submit" data-loading-text="回复中.."
                                       value="回复">
                            </div>
                        </div>
                    </div>

                    <input type="hidden" name="topic_id" value="{{ topic.id }}">
                </form>
            </div>
        </div>

    </div>
</div>

<script>
    var log = console.log.bind(console)
    var e = (sel) => document.querySelector(sel)
    var es = (sel) => document.querySelectorAll(sel)

    var pylpMd = function() {
        var editor = new Editor()
        editor.render(e('.editor')[0])
    }

    var topicMd = function() {
        var a = e('.p-topic-text')
        var tContent = []
        var k = a.dataset.key
        tContent.push(k)
        var v = a.innerHTML
        tContent.push(v)
        var t = 'id-topic-text-' + k
        document.getElementById(t).innerHTML = marked(v)
    }

    var repliesMd = function() {
        var a = es('.p-text')
        var listContent = []
        for(let i = 0; i < a.length; i++) {
            var lContent = []
            var k = a[i].dataset.key
            lContent.push(k)
            var v = a[i].innerHTML
            lContent.push(v)
            listContent.push(lContent)

        }
        log('objContent',typeof listContent,listContent)
        for (var j = 0; j < listContent.length; j++) {
            let a = listContent[j]
            var t = 'id-editor-text-' + a[0]
            document.getElementById(t).innerHTML = marked(a[1])
        }
    }


    repliesMd()
    topicMd()
    pylpMd()


</script>

{% endblock %}

templates/topic/index.html
{% extends "base.html" %}

{% block title %}
    topic.index
{% endblock %}


{% block content %}

<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="inner">
                <a href="/py/topic/new" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/py/topic"
                   class="topic-tab current-tab">
                    全部
                </a>

                {% for b in bs %}
                <a href="/py/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">

                            <a class="user_avatar pull-left">
                                 <img src={{ '/py/uploads/' + t.user().user_image + '?v=3&amp;s=120' }}
                            title="atian25"/>
                            </a>

                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                            </a>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>

{% endblock %}

templates/topic/new.html
{% extends "base.html" %}

{% block title %}
    topic.new
{% endblock %}


{% block content %}


<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
<fieldset>
    <textarea autofocus class='span9' id='title'
              name='title' rows='1'
              placeholder="标题"></textarea>
    <span class="tab-selector">选择版块：</span>
    <select name="board_id" id="board" required>
        <option value="">请选择</option>
            {% for b in bs %}
            <option value="{{ b.id }}">{{ b.title }}</option>
            {% endfor %}
    </select>
    <div class='markdown_editor in_editor'>
      <div class='markdown_in_editor'>
        <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
        <div class='editor_buttons'>
          <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
        </div>
      </div>
    </div>
</fieldset>
</form>
            </div>
        </div>
    </div>
</div>

<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>

{% endblock %}

templates/topic/topic.html
{% extends "base.html" %}

{% block title %}
    topic
{% endblock %}

{% block content %}

<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                    <fieldset>
                        <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题"></textarea>
                        <div class='markdown_editor in_editor'>
                          <div class='markdown_in_editor'>
                            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                            <div class='editor_buttons'>
                              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                            </div>
                          </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>

{% endblock %}